### ISSUE TITLE
I can't get it to build on neither Win 7 or Debian Jessie 8.5

### ISSUE THREAD

**Issue by Jovaage** [justinleewells/pogo-optimizer#1]
When running npm install on either system, it terminates with this:

For Windows 7
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\pogo-optimizer\npm-debug.log

C:\pogo-optimizer master (59f5565) [origin/master] (pogo-optimizer@0.0.1)
λ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@6.2.2 | win32 | x64
gyp info spawn C:\Program Files\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\jova\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\pogo-optimizer\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jova\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jova\\.node-gyp\\6.2.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jova\\.node-gyp\\6.2.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\jova\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\pogo-optimizer',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\pogo-optimizer\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: C:\pogo-optimizer) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\jova\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jova\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\pogo-optimizer
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
```  

For Debian Jessie 8.5
```
> node-gyp rebuild

lp.sh: 1: lp.sh: pkg-config: not found
gyp: Call to 'sh lp.sh' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" gyp ERR! cwd /home/vaage/pogo-optimizer/node_modules/node-protobuf
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
pogo-optimizer@0.0.1 /home/vaage/pogo-optimizer
├─┬ express@4.14.0
│ ├─┬ accepts@1.3.3
│ │ ├─┬ mime-types@2.1.11
│ │ │ └── mime-db@1.23.0
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.1
│ ├── content-type@1.0.2
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── depd@1.1.0
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.7.0
│ ├─┬ finalhandler@0.5.0
│ │ ├── statuses@1.3.0
│ │ └── unpipe@1.0.0
│ ├── fresh@0.3.0
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.1.2
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.1.1
│ ├── qs@6.2.0
│ ├── range-parser@1.2.0
│ ├─┬ send@0.14.1
│ │ ├── destroy@1.0.4
│ │ ├─┬ http-errors@1.5.0
│ │ │ ├── inherits@2.0.1
│ │ │ └── setprototypeof@1.0.1
│ │ └── mime@1.3.4
│ ├── serve-static@1.11.1
│ ├─┬ type-is@1.6.13
│ │ └── media-typer@0.3.0
│ ├── utils-merge@1.0.0
│ └── vary@1.1.0
├── jsonfile@2.3.1
└── lodash@4.13.1

npm WARN pogo-optimizer@0.0.1 No repository field.
npm WARN pogo-optimizer@0.0.1 No license field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.
```

**Comment by esfomeado** [comment]
Same problem on Windows 10.

**Comment by Maxxxel** [comment]
jup

**Comment by eratio08** [comment]
on the mac I had to "brew install protobuf" because it was missing on my PATH

so try to manualy install protobuf

**Comment by Maxxxel** [comment]
still this: failed at ......  `node-gyp rebuild`

**Comment by Maxxxel** [comment]
C:\pogo-optimizer-master\node_modules\node-protobuf\build\protobuf.vcxproj(20,3): error MSB4019

**Comment by justinleewells** [comment]
I think that the error with this one is definitely that you're missing protobuf. Any chance you could install that and retry, @Jovaage?

**Comment by Jovaage** [comment]
I just installed protobuf using this [script](https://gist.github.com/samklr/0b8a0620f82005e7f556), and I get the exact same result on debian

**Comment by eratio08** [comment]
you still need to add it to your path to that other tools can find it, I guess

**Comment by eratio08** [comment]
does the last line of the script work? can you call protobuf from the shell?

**Comment by Jovaage** [comment]
Yep,
```
$ protoc --version
libprotoc 2.6.1
```

**Comment by andrewda** [comment]
Yup, installing protobuf fixed the issue for me on both Mac OS 10.11 and Debian.

**Comment by eratio08** [comment]
protobuf aka "protoc" is needed for https://github.com/fuwaneko/node-protobuf which a wrapping protoc for node - a fix might be found on the projects page

**Comment by Maxxxel** [comment]
now i have to figure it out for win10 :/

**Comment by eratio08** [comment]
There is a description for windows too - is the windows package manger released - you could try it
http://www.howtogeek.com/224111/how-to-use-packagemanagement-aka-oneget-on-windows-10/

**Comment by Maxxxel** [comment]
ill give it a try

**Comment by eratio08** [comment]
you could try to install protoc aka protobuf with it. I have no clue how the windows pm works but it could make things easier if it works like other package managers i.e. brew for mac

**Comment by brycesub** [comment]
I think I'm pretty close to getting this to work on Windows 10.  I have VC2015 Community installed, I copied the "google" folder from the protobuf-c\src sources to the "C:\program files (x86)\Microsoft Visual Studio 14.0\VC\Include and run npm install.  I get the following error:

`  ..\src\parse.cpp(83): note: see reference to function template instantiation 'v8::Local<v8::Number> Nan::New<v8::Number,google::protobuf::uint64>(A0)' being compiled
          with
          [
              A0=google::protobuf::uint64
          ]
  win_delay_load_hook.cc
LINK : warning LNK4044: unrecognized option '/L%LIBPROTOBUF%\lib.lib'; ignored [C:\pogo-optimizer\node_modules\pokemon-go-mitm-node\node_modules\node-protobuf\build\protobuf.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'libprotobuf.lib' [C:\pogo-optimizer\node_modules\pokemon-go-mitm-node\node_modules\node-protobuf\build\protobuf.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\bryce\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bryce\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\pogo-optimizer\node_modules\pokemon-go-mitm-node\node_modules\node-protobuf
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\pogo-optimizer\node_modules\node-protobuf\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\pogo-optimizer\node_modules\pokemongo-protobuf\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\pogo-optimizer\node_modules\pokemongo-protobuf\node_modules\node-protobuf\package.json'
npm WARN pogo-optimizer@0.0.2 No repository field.
npm WARN pogo-optimizer@0.0.2 No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bryce\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\pogo-optimizer\npm-debug.log`

**Comment by Maxxxel** [comment]
npm ERR! Failed at the node-protobuf@1.3.0 install script 'node-gyp rebuild'.

same as me nvm what i do

**Comment by Maxxxel** [comment]
I give it up.

**Comment by justinleewells** [comment]
Sorry, Maxxxel. This was originally just intended to be a OSX project. I'll be working on an Electron version later tonight though.

**Comment by Maxxxel** [comment]
Who uses OSX :P

**Comment by esfomeado** [comment]
@justinleewells thanks for your effort with the Electron version.

**Comment by andrewda** [comment]
@justinleewells an Electron version would be fantastic! I've had quite a lot of experience using Electron, so I would love to contribute once you publish it.

**Comment by MonsterMMORPG** [comment]
@Maxxxel  same here

please release a version for Windows

**Comment by CannibalVox** [comment]
Having same issues as windows users on el capitan. 

f45c89a226cb:pogo-optimizer baynhams$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.3.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/baynhams/stuff/pogo-optimizer/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/baynhams/.node-gyp/6.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/baynhams/.node-gyp/6.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/baynhams/stuff/pogo-optimizer',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/baynhams/stuff/pogo-optimizer) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/baynhams/stuff/pogo-optimizer
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
f45c89a226cb:pogo-optimizer baynhams$

**Comment by mrawesome1337** [comment]
I'm trying to get this up on a linux distro has anyone had any luck? I'm getting the same errors posted above. I just setup a fresh ubuntu install 16.04. I installed nodejs, build-essential, npm, protobuf, protobuf-compiler, nad bower. I git cloned the project and called npm install. Is there any way to get this installed on a linux distro? I spent most of the day trying to get it installed on windows and came to the same conclusion. I even compiled the protobuf lib, but 5 test cases failed when I ran the check (out of ~1900). I seemed to receive the same error.

Any advice?

**Comment by n2o** [comment]
@mrawesome1337 I successfully installed it using Docker (see #21). In the Dockerfile are all steps which need to be pasted to the console (except for the installation of nodejs), if you want to install it directly on your computer.

**Comment by mrawesome1337** [comment]
@n2o You are my hero. I'll try this when I get back. I originally started trying to set this up in docker so it wont take me long to get setup. I had already resigned myself to writing my own so this is very good news. :)

**Comment by pdavid0** [comment]
Still can't make it work on El Capitan, tried every command I found around here.

node 4.4.5
npm 3.10.5

Error : 
```
In file included from ../src/init.cpp:1:
../src/common.h:11:10: fatal error: 'google/protobuf/descriptor.h' file not found
#include <google/protobuf/descriptor.h>
```

**Comment by eratio08** [comment]
@pdavid0 did you try `brew install protobuf`?

**Comment by pdavid0** [comment]
@eratio08 Thanks for that, it seems it was a bad symlink, removed everything and relinked.

**Comment by Maxxxel** [comment]
cant w8 for windows..

**Comment by Guiver** [comment]
`Is there any way to get this installed on a linux distro?`
Yes, it's working with a little Virtual Machine (512 RAM/1 Proc/~2GO HDD).
Install Debian 8 x64 without desktop and try this :
> apt-get install -y curl build-essential libprotobuf-dev git pkg-config
> curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
> apt-get install nodejs
> npm install -g bower
> git clone https://github.com/justinleewells/pogo-optimizer
> cd pogo-optimizer
> npm install
> bower install --allow-root
> node index
After, you can access to the web page with your host (or another PC on the same network) "ip.server:3000"
All is working for me now.
