### ISSUE TITLE
docker container broken?

### ISSUE THREAD

**Issue by l3iggs** [justinleewells/pogo-optimizer#105]
built locally from the Dockerfile in the master branch:
```
$ docker run -p 3000:3000 -p 8081:8081 -it pogo
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.0
npm info lifecycle pogo-optimizer@1.1.0~prestart: pogo-optimizer@1.1.0
npm info lifecycle pogo-optimizer@1.1.0~start: pogo-optimizer@1.1.0

> pogo-optimizer@1.1.0 start /code
> gulp && node index

(node:18) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[21:20:21] Using gulpfile /code/gulpfile.js
[21:20:21] Starting 'clean'...
[21:20:21] Finished 'clean' after 89 ms
[21:20:21] Starting 'jade'...
[21:20:21] Starting 'stylus'...
[21:20:21] Starting 'img'...
[21:20:21] Starting 'lib-js'...
[21:20:21] Starting 'lib-css'...
[21:20:21] Starting 'favicon'...
[21:20:21] Starting 'js'...
[21:20:21] Starting 'font'...
[21:20:21] Finished 'favicon' after 245 ms
[21:20:21] Finished 'lib-css' after 253 ms
[21:20:21] Finished 'stylus' after 357 ms
[21:20:21] Finished 'lib-js' after 369 ms
[21:20:21] Finished 'js' after 418 ms
[21:20:21] Finished 'jade' after 442 ms
[21:20:21] Finished 'font' after 546 ms
[21:20:22] Finished 'img' after 801 ms
[21:20:22] Starting 'default'...
[21:20:22] Finished 'default' after 3.28 μs
/code/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /code/node_modules/node-protobuf/build/Release/protobuf.node)
  at Error (native)
  at Object.Module._extensions..node (module.js:568:18)
  at Module.load (/code/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at bindings (/code/node_modules/bindings/bindings.js:76:44)
  at Object.<anonymous> (/code/node_modules/node-protobuf/protobuf.js:9:35)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (/code/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/code/node_modules/pokemongo-protobuf/index.js:2:16)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (/code/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/code/node_modules/pokemon-go-mitm/lib/pokemon-go-mitm.coffee:7:14)
  at Object.<anonymous> (/code/node_modules/pokemon-go-mitm/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:541:32)
  at Object.loadFile (/code/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/code/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/code/node_modules/pokemon-go-mitm/index.js:2:18)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/code/index.js:22:21)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.runMain (module.js:575:10)
  at run (bootstrap_node.js:352:7)
  at startup (bootstrap_node.js:144:9)
  at bootstrap_node.js:467:3


npm info lifecycle pogo-optimizer@1.1.0~start: Failed to exec start script
npm ERR! Linux 4.6.4-1-ARCH
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pogo-optimizer@1.1.0 start: `gulp && node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pogo-optimizer@1.1.0 start script 'gulp && node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogo-optimizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /code/npm-debug.log
```

**Comment by l3iggs** [comment]
invalid
