### ISSUE TITLE
can't run the program

### ISSUE THREAD

**Issue by yidongw** [justinleewells/pogo-optimizer#112]
Failed at the pogo-optimizer@1.2.0 start script 'gulp && node index'.
npm ERR! This is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/******/Documents/pogo-optimizer/npm-debug.log

Well I can't find the log anywhere

**Comment by patrickhahn** [comment]
Same issue here. Full output

```
> pogo-optimizer@1.2.0 start /Users/patrick.hahn/notwork/pogo-optimizer
> gulp && node index

(node:72477) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[12:42:48] Using gulpfile ~/notwork/pogo-optimizer/gulpfile.js
[12:42:48] Starting 'clean'...
[12:42:48] Finished 'clean' after 129 ms
[12:42:48] Starting 'jade'...
[12:42:48] Starting 'stylus'...
[12:42:48] Starting 'img'...
[12:42:48] Starting 'lib-js'...
[12:42:48] Starting 'lib-css'...
[12:42:48] Starting 'favicon'...
[12:42:48] Starting 'js'...
[12:42:48] Starting 'font'...
[12:42:48] Finished 'favicon' after 233 ms
[12:42:48] Finished 'lib-css' after 241 ms
[12:42:48] Finished 'stylus' after 371 ms
[12:42:48] Finished 'lib-js' after 421 ms
[12:42:48] Finished 'js' after 439 ms
[12:42:48] Finished 'jade' after 474 ms
[12:42:49] Finished 'font' after 707 ms
[12:42:49] Finished 'img' after 1.15 s
[12:42:49] Starting 'default'...
[12:42:49] Finished 'default' after 3.33 μs
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
Pokemon GO Optimizer front-end listening on port 3000
Accept the cert at 127.0.0.1:3000/ca.pem if you haven't already done so
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8081
  at Object.exports._errnoException (util.js:1007:11)
  at exports._exceptionWithHostPort (util.js:1030:20)
  at Server._listen2 (net.js:1253:14)
  at listen (net.js:1289:10)
  at Server.listen (net.js:1385:5)
  at /Users/patrick.hahn/notwork/pogo-optimizer/node_modules/http-mitm-proxy/lib/proxy.js:86:23
  at /Users/patrick.hahn/notwork/pogo-optimizer/node_modules/http-mitm-proxy/lib/ca.js:132:12
  at /Users/patrick.hahn/notwork/pogo-optimizer/node_modules/async/lib/async.js:726:13
  at /Users/patrick.hahn/notwork/pogo-optimizer/node_modules/async/lib/async.js:52:16
  at /Users/patrick.hahn/notwork/pogo-optimizer/node_modules/async/lib/async.js:269:32
  at /Users/patrick.hahn/notwork/pogo-optimizer/node_modules/async/lib/async.js:44:16
  at /Users/patrick.hahn/notwork/pogo-optimizer/node_modules/async/lib/async.js:723:17
  at /Users/patrick.hahn/notwork/pogo-optimizer/node_modules/async/lib/async.js:167:37
  at /Users/patrick.hahn/notwork/pogo-optimizer/node_modules/http-mitm-proxy/lib/ca.js:192:12
  at /Users/patrick.hahn/notwork/pogo-optimizer/node_modules/async/lib/async.js:52:16
  at /Users/patrick.hahn/notwork/pogo-optimizer/node_modules/async/lib/async.js:550:17
  at /Users/patrick.hahn/notwork/pogo-optimizer/node_modules/async/lib/async.js:544:17
  at _arrayEach (/Users/patrick.hahn/notwork/pogo-optimizer/node_modules/async/lib/async.js:85:13)
  at Immediate.taskComplete (/Users/patrick.hahn/notwork/pogo-optimizer/node_modules/async/lib/async.js:543:13)
  at tryOnImmediate (timers.js:543:15)
  at processImmediate [as _immediateCallback] (timers.js:523:5)


npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! pogo-optimizer@1.2.0 start: `gulp && node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pogo-optimizer@1.2.0 start script 'gulp && node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogo-optimizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/patrick.hahn/notwork/pogo-optimizer/npm-debug.log
```

**Comment by alexanderhektor** [comment]
same here..

although slightly more current versions
node: 6.3.1
npm 3.10.3




`> pogo-optimizer@1.2.0 start /Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer
> gulp && node index

(node:51641) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[19:16:43] Using gulpfile ~/Google Drive/Coden/pokemoniv/pogo-optimizer/gulpfile.js
[19:16:43] Starting 'clean'...
[19:16:43] Finished 'clean' after 180 ms
[19:16:43] Starting 'jade'...
[19:16:43] Starting 'stylus'...
[19:16:43] Starting 'img'...
[19:16:43] Starting 'lib-js'...
[19:16:43] Starting 'lib-css'...
[19:16:43] Starting 'favicon'...
[19:16:43] Starting 'js'...
[19:16:43] Starting 'font'...
[19:16:43] Finished 'lib-css' after 131 ms
[19:16:43] Finished 'favicon' after 131 ms
[19:16:44] Finished 'stylus' after 488 ms
[19:16:44] Finished 'lib-js' after 560 ms
[19:16:44] Finished 'js' after 635 ms
[19:16:44] Finished 'jade' after 671 ms
[19:16:44] Finished 'font' after 993 ms
[19:16:45] Finished 'img' after 1.9 s
[19:16:45] Starting 'default'...
[19:16:45] Finished 'default' after 6.29 μs
/Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module did not self-register.
  at Error (native)
  at Object.Module._extensions..node (module.js:568:18)
  at Module.load (/Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at bindings (/Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/node_modules/bindings/bindings.js:76:44)
  at Object.<anonymous> (/Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/node_modules/node-protobuf/protobuf.js:9:35)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (/Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/node_modules/pokemongo-protobuf/index.js:2:16)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (/Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/node_modules/pokemon-go-mitm/lib/pokemon-go-mitm.coffee:7:14)
  at Object.<anonymous> (/Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/node_modules/pokemon-go-mitm/lib/pokemon-go-mitm.coffee:1:1)
  at Module._compile (module.js:541:32)
  at Object.loadFile (/Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/node_modules/pokemon-go-mitm/index.js:2:18)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/index.js:22:21)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.runMain (module.js:575:10)
  at run (bootstrap_node.js:352:7)
  at startup (bootstrap_node.js:144:9)
  at bootstrap_node.js:467:3


npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pogo-optimizer@1.2.0 start: `gulp && node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pogo-optimizer@1.2.0 start script 'gulp && node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogo-optimizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alex/Google Drive/Coden/pokemoniv/pogo-optimizer/npm-debug.log
alex@alex-mbp:~/Google Drive/Coden/pokemoniv/pogo-optimizer$`

**Comment by chrisbosch1013** [comment]
I am also having the same issue :-(

Chriss-MBP:pogo-optimizer chrisbosch$ npm install
npm WARN package.json pogo-optimizer@1.2.0 No repository field.
npm WARN package.json pogo-optimizer@1.2.0 No license field.
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
 
> node-protobuf@1.3.2 install /Users/chrisbosch/pogo-optimizer/node_modules/pokemon-go-mitm/node_modules/pokemongo-protobuf/node_modules/node-protobuf
> node-gyp rebuild

lp.sh: line 2: pkg-config: command not found
gyp: Call to 'sh lp.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/chrisbosch/pogo-optimizer/node_modules/pokemon-go-mitm/node_modules/pokemongo-protobuf/node_modules/node-protobuf
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-protobuf@1.3.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chrisbosch/pogo-optimizer/npm-debug.log

**Comment by justinleewells** [comment]
@chrisbosch1013 It looks like you need to run `brew install pkg-config`

**Comment by chrisbosch1013** [comment]
@justinleewells Thank you for the quick reply.  When I try to run the brew commands, I get a "-bash: brew: command not found" message.  Do I need to have something else installed?

**Comment by justinleewells** [comment]
Ah, you need to download homebrew from brew.sh.

**Comment by chrisbosch1013** [comment]
@justinleewells Got it all working!  Thank you for the help!

**Comment by alexanderhektor** [comment]
Updated brew and reinstalled everything. Git seemed to have missing symlinks here. Not sure that was the issue, but now it worked. Having other problems now..

**Comment by justinleewells** [comment]
If you're having the ca.pem error, it should be fixed once the new Docker image builds @alexanderhektor. Give it 10-15 minutes
