### ISSUE TITLE
npm run install-libs error

### ISSUE THREAD

**Issue by eagle132** [justinleewells/pogo-optimizer#113]
I had no issues running your previous version of pogo-optimizer, but this one is causing me issues when I run "npm run install-libs"

Here's the log:

```
bryces-Mac:pogo-optimizer bryce$ npm run install-libs

> pogo-optimizer@1.2.0 install-libs /Users/bryce/Documents/pogo-optimizer
> bower install

/Users/bryce/Documents/pogo-optimizer/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/Users/bryce/.config/configstore/bower-github.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.create.all.get (/Users/bryce/Documents/pogo-optimizer/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/Users/bryce/Documents/pogo-optimizer/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/Users/bryce/Documents/pogo-optimizer/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/Users/bryce/Documents/pogo-optimizer/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/Users/bryce/Documents/pogo-optimizer/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "run" "install-libs"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pogo-optimizer@1.2.0 install-libs: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pogo-optimizer@1.2.0 install-libs script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogo-optimizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bryce/Documents/pogo-optimizer/npm-debug.log

Any ideas? Thanks! Love the app!
```

**Comment by justinleewells** [comment]
Try `sudo npm run install-libs`

**Comment by eagle132** [comment]
I had actually tried that as well, sorry I should have mentioned that:

```
bryces-Mac:pogo-optimizer bryce$ sudo npm run install-libs --allow-root

> pogo-optimizer@1.2.0 install-libs /Users/bryce/Documents/pogo-optimizer
> bower install

bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "run" "install-libs" "--allow-root"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pogo-optimizer@1.2.0 install-libs: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pogo-optimizer@1.2.0 install-libs script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogo-optimizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bryce/Documents/pogo-optimizer/npm-debug.log
```

**Comment by justinleewells** [comment]
Okay, try `bower install` and `sudo bower --allow-root install`. One of those should work.

**Comment by eagle132** [comment]
Still seems to give me the same error. Weird... thanks for the assistance

**Comment by LLLZHEN** [comment]
try `sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config`

It works for me.

**Comment by eagle132** [comment]
I cleared out everything and tried again with the sudo bower --allow-root install and it works :) thanks!!

**Comment by thetof91** [comment]
I got the same problem?
But was the command you used and where did you use it?

**Comment by nubs** [comment]
The chown commands listed above are likely the ones that fixed it - you just need to run them in a terminal
