### ISSUE TITLE
.http-mitm-proxy not generated in Dockerhub image

### ISSUE THREAD

**Issue by daveenguyen** [justinleewells/pogo-optimizer#133]
When I try to use `justinleewells/pogo-optimizer` image,
it does not have `.http-mitm-proxy` folder generated inside the container.

It fails with the following
```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '.http-mitm-proxy/certs/ca.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/code/index.js:20:46)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)

npm info lifecycle pogo-optimizer@1.3.0~start: Failed to exec start script
npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pogo-optimizer@1.3.0 start: `gulp && node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pogo-optimizer@1.3.0 start script 'gulp && node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogo-optimizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /code/npm-debug.log
```

The code fails at the following code because it cannot open file `ca.pem` because it wasn't generated yet.
```js
if (!fs.existsSync(__dirname + '/.htt-mitm-proxy/certs/ca.crt')) {
  var cert = forge.pki.certificateFromPem(fs.readFileSync('.http-mitm-proxy/certs/ca.pem'));
  fs.writeFile('.http-mitm-proxy/certs/ca.crt', forge.asn1.toDer(forge.pki.certificateToAsn1(cert)).getBytes(), {encoding: 'binary'});
}
```

I found [pokemon-go-mitm's README](https://github.com/rastapasta/pokemon-go-mitm-node/blob/master/README.md) and it says to run an example to generate the certificate.

If I comment the code where it failed, `node index` generates the `.http-mitm-proxy` folder.

I think we could add a quick run of an example or some way to generate the certificate as part of the Dockerfile

**Comment by ChristRespawns** [comment]
I am getting this error when using a Mac.

**Comment by justinleewells** [comment]
Fixed in justinleewells/pogo-optimizer@29dfdd5

**Comment by ChristRespawns** [comment]
It worked fine this morning, but I’m getting the same error now.

**Comment by justinleewells** [comment]
You need to pull the newest version @ChristRespawns.

**Comment by ChristRespawns** [comment]
Without sounding totally dumb, how do I do that?

**Comment by justinleewells** [comment]
`cd pogo-optimizer && git pull && npm start` try that

**Comment by ChristRespawns** [comment]
That worked. Thanks for the help!

**Comment by justinleewells** [comment]
No problem!
