### ISSUE TITLE
Fails to start - error with http-mitm-proxy

### ISSUE THREAD

**Issue by TheImmortal** [justinleewells/pogo-optimizer#134]
```
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
Pokemon GO Optimizer front-end listening on port 3000
/Users/theimmortal/pogo-optimizer/node_modules/pokemon-go-mitm/node_modules/http-mitm-proxy/lib/proxy.js:62
      return callback(err);
             ^

TypeError: callback is not a function
  at /Users/theimmortal/pogo-optimizer/node_modules/pokemon-go-mitm/node_modules/http-mitm-proxy/lib/proxy.js:62:14
  at /Users/theimmortal/pogo-optimizer/node_modules/pokemon-go-mitm/node_modules/http-mitm-proxy/lib/ca.js:130:14
  at /Users/theimmortal/pogo-optimizer/node_modules/async/lib/async.js:726:13
  at /Users/theimmortal/pogo-optimizer/node_modules/async/lib/async.js:52:16
  at /Users/theimmortal/pogo-optimizer/node_modules/async/lib/async.js:264:21
  at /Users/theimmortal/pogo-optimizer/node_modules/async/lib/async.js:44:16
  at /Users/theimmortal/pogo-optimizer/node_modules/async/lib/async.js:723:17
  at /Users/theimmortal/pogo-optimizer/node_modules/async/lib/async.js:167:37
  at /Users/theimmortal/pogo-optimizer/node_modules/pokemon-go-mitm/node_modules/http-mitm-proxy/lib/ca.js:185:14
  at /Users/theimmortal/pogo-optimizer/node_modules/async/lib/async.js:52:16
  at ReadFileContext.<anonymous> (/Users/theimmortal/pogo-optimizer/node_modules/async/lib/async.js:570:21)
  at ReadFileContext.callback (/Users/theimmortal/pogo-optimizer/node_modules/async/lib/async.js:167:37)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
```

On OS X.

**Comment by yy307** [comment]
I have the same error on OS X EI

**Comment by justinleewells** [comment]
Fixed in justinleewells/pogo-optimizer@29dfdd5

**Comment by TheImmortal** [comment]
That doesn't fix it...

**Comment by justinleewells** [comment]
Oh, my bad. I thought this was the same as the other ca.pem ones. I'll look into it in a bit.

**Comment by g3r4n** [comment]
```
npm install -g coffee-script
coffee node_modules/pokemon-go-mitm/example.logTraffic.coffee
```
do ctrl + c.
`npm start`

**Comment by justinleewells** [comment]
This appears to be an upstream issue. Do you have this error with the latest version, @TheImmortal?

**Comment by TheImmortal** [comment]
Yes, I still have the error.

@g3r4n I get the same error when I run that.

**Comment by justinleewells** [comment]
Are you sure that you properly updated to v1.3.2?

**Comment by TheImmortal** [comment]
Yes I'm sure.

v6.3.1 and 3.10.5

**Comment by TheImmortal** [comment]
Note: If remove ``callback(err)`` from line 62 and leave it as ``return;`` then this works fine!
