### ISSUE TITLE
Mac OSX Command Errors

### ISSUE THREAD

**Issue by ChristRespawns** [justinleewells/pogo-optimizer#138]
I was having trouble with the "brew" and "npm" commands until I installed homebrew. Now, I receive errors on the final command:

```
Andrews-MacBook-Air:pogo-optimizer Andrew$ npm start

> pogo-optimizer@1.3.0 start /Users/Andrew/pogo-optimizer/pogo-optimizer
> gulp && node index

(node:1063) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[09:07:12] Using gulpfile ~/pogo-optimizer/pogo-optimizer/gulpfile.js
[09:07:12] Starting 'clean'...
[09:07:12] Finished 'clean' after 4.9 ms
[09:07:12] Starting 'jade'...
[09:07:12] Starting 'stylus'...
[09:07:12] Starting 'img'...
[09:07:12] Starting 'lib-js'...
[09:07:12] Starting 'lib-css'...
[09:07:12] Starting 'favicon'...
[09:07:12] Starting 'js'...
[09:07:12] Starting 'font'...
[09:07:12] Finished 'lib-css' after 258 ms
[09:07:12] Finished 'favicon' after 454 ms
[09:07:13] Finished 'stylus' after 669 ms
[09:07:13] Finished 'lib-js' after 761 ms
[09:07:13] Finished 'jade' after 936 ms
[09:07:13] Finished 'js' after 905 ms
[09:07:13] Finished 'font' after 1.12 s
[09:07:14] Finished 'img' after 1.78 s
[09:07:14] Starting 'default'...
[09:07:14] Finished 'default' after 6.72 μs
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '.http-mitm-proxy/certs/ca.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/Users/Andrew/pogo-optimizer/pogo-optimizer/index.js:20:46)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pogo-optimizer@1.3.0 start: `gulp && node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pogo-optimizer@1.3.0 start script 'gulp && node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogo-optimizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.
```

**Comment by ChristRespawns** [comment]
Edit, other user having similar issue. Closing this.
