### ISSUE TITLE
Error: Cannot find module 'quick-local-ip'

### ISSUE THREAD

**Issue by ChristRespawns** [justinleewells/pogo-optimizer#171]
Not sure what the issue is. Worked fine last night using this `cd pogo-optimizer && git pull && npm start`

but now I get this error:

```
> pogo-optimizer@1.3.2 start /Users/Andrew/pogo-optimizer/pogo-optimizer
> gulp && node index

(node:744) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[17:26:35] Using gulpfile ~/pogo-optimizer/pogo-optimizer/gulpfile.js
[17:26:35] Starting 'clean'...
[17:26:36] Finished 'clean' after 160 ms
[17:26:36] Starting 'jade'...
[17:26:36] Starting 'stylus'...
[17:26:36] Starting 'img'...
[17:26:36] Starting 'lib-js'...
[17:26:36] Starting 'lib-css'...
[17:26:36] Starting 'favicon'...
[17:26:36] Starting 'js'...
[17:26:36] Starting 'font'...
[17:26:36] Finished 'lib-css' after 361 ms
[17:26:36] Finished 'favicon' after 361 ms
[17:26:36] Finished 'stylus' after 554 ms
[17:26:36] Finished 'lib-js' after 718 ms
[17:26:36] Finished 'js' after 725 ms
[17:26:36] Finished 'jade' after 765 ms
[17:26:37] Finished 'font' after 916 ms
[17:26:37] Finished 'img' after 1.49 s
[17:26:37] Starting 'default'...
[17:26:37] Finished 'default' after 7.66 μs
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
Pokemon GO Optimizer front-end listening on port 3000
module.js:442
    throw err;
    ^

Error: Cannot find module 'quick-local-ip'
  at Function.Module._resolveFilename (module.js:440:15)
  at Function.Module._load (module.js:388:25)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Server.<anonymous> (/Users/Andrew/pogo-optimizer/pogo-optimizer/index.js:125:12)
  at Server.g (events.js:286:16)
  at emitNone (events.js:86:13)
  at Server.emit (events.js:185:7)
  at emitListeningNT (net.js:1278:10)
  at _combinedTickCallback (internal/process/next_tick.js:71:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at Module.runMain (module.js:577:11)
  at run (bootstrap_node.js:352:7)
  at startup (bootstrap_node.js:144:9)
  at bootstrap_node.js:467:3


npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pogo-optimizer@1.3.2 start: `gulp && node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pogo-optimizer@1.3.2 start script 'gulp && node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogo-optimizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Andrew/pogo-optimizer/pogo-optimizer/npm-debug.log
```

**Comment by justinleewells** [comment]
`npm install && npm start`
