### ISSUE TITLE
public/assets/lib doesn't exist - 404s for js

### ISSUE THREAD

**Issue by JonnyPower** [justinleewells/pogo-optimizer#196]
The front-end doesn't have the lib folders causing http 404 when trying to load the frontend js.

> [meeseeks] root pogo-optimizer $ ls public/assets/
css  img

![Request errors](http://i.imgur.com/d49EOG3.png)

Setup: 
- CentOS Linux release 7.2.1511 (Core) 
- node v6.2.2
- npm 3.9.5

Not very familiar with node but I can't run `npm run install-libs` as I'm running it as root;

```
> pogo-optimizer@1.3.2 install-libs /root/pogo-optimizer
> bower install

bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "run" "install-libs"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! pogo-optimizer@1.3.2 install-libs: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pogo-optimizer@1.3.2 install-libs script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogo-optimizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/pogo-optimizer/npm-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/bin/npm', 'run', 'install-libs' ]
2 info using npm@3.10.5
3 info using node@v6.2.2
4 verbose run-script [ 'preinstall-libs', 'install-libs', 'postinstall-libs' ]
5 info lifecycle pogo-optimizer@1.3.2~preinstall-libs: pogo-optimizer@1.3.2
6 silly lifecycle pogo-optimizer@1.3.2~preinstall-libs: no script for preinstall-libs, continuing
7 info lifecycle pogo-optimizer@1.3.2~install-libs: pogo-optimizer@1.3.2
8 verbose lifecycle pogo-optimizer@1.3.2~install-libs: unsafe-perm in lifecycle true
9 verbose lifecycle pogo-optimizer@1.3.2~install-libs: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/pogo-optimizer/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
10 verbose lifecycle pogo-optimizer@1.3.2~install-libs: CWD: /root/pogo-optimizer
11 silly lifecycle pogo-optimizer@1.3.2~install-libs: Args: [ '-c', 'bower install' ]
12 silly lifecycle pogo-optimizer@1.3.2~install-libs: Returned: code: 1  signal: null
13 info lifecycle pogo-optimizer@1.3.2~install-libs: Failed to exec install-libs script
14 verbose stack Error: pogo-optimizer@1.3.2 install-libs: `bower install`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid pogo-optimizer@1.3.2
16 verbose cwd /root/pogo-optimizer
17 error Linux 3.10.0-327.10.1.el7.x86_64
18 error argv "/usr/local/bin/node" "/usr/bin/npm" "run" "install-libs"
19 error node v6.2.2
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error pogo-optimizer@1.3.2 install-libs: `bower install`
22 error Exit status 1
23 error Failed at the pogo-optimizer@1.3.2 install-libs script 'bower install'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pogo-optimizer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     bower install
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pogo-optimizer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pogo-optimizer
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by JonnyPower** [comment]
I changed `package.json`'s `bower install` to `bower install --allow-root` - everything works now
