### ISSUE TITLE
Error when transferring pokemon

### ISSUE THREAD

**Issue by snicker** [justinleewells/pogo-optimizer#20]
```
TypeError: Cannot read property 'pokemon_data' of undefined
  at /usr/home/snicker/devel/node/pogo-optimizer/index.js:60:36
  at arrayReduce (/usr/home/snicker/devel/node/pogo-optimizer/node_modules/lodash/lodash.js:618:21)
  at Function.reduce (/usr/home/snicker/devel/node/pogo-optimizer/node_modules/lodash/lodash.js:8979:14)
  at /usr/home/snicker/devel/node/pogo-optimizer/index.js:59:19
  at PokemonGoMITM.handleResponse (/usr/home/snicker/devel/node/pogo-optimizer/node_modules/pokemon-go-mitm/lib/pokemon-go-mitm.coffee:157:14)
  at /usr/home/snicker/devel/node/pogo-optimizer/node_modules/pokemon-go-mitm/lib/pokemon-go-mitm.coffee:118:27
  at /usr/home/snicker/devel/node/pogo-optimizer/node_modules/http-mitm-proxy/lib/proxy.js:1008:12
  at /usr/home/snicker/devel/node/pogo-optimizer/node_modules/async/lib/async.js:181:20
  at Object.async.forEachOf.async.eachOf (/usr/home/snicker/devel/node/pogo-optimizer/node_modules/async/lib/async.js:233:13)
  at Object.async.forEach.async.each (/usr/home/snicker/devel/node/pogo-optimizer/node_modules/async/lib/async.js:209:22)
  at Proxy._onResponseEnd (/usr/home/snicker/devel/node/pogo-optimizer/node_modules/http-mitm-proxy/lib/proxy.js:1007:9)
  at end (/usr/home/snicker/devel/node/pogo-optimizer/node_modules/http-mitm-proxy/lib/proxy.js:844:20)
  at Gunzip.onend (_stream_readable.js:512:10)
  at Gunzip.g (events.js:286:16)
  at emitNone (events.js:91:20)
  at Gunzip.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:973:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

pogo-optimizer crashes with that error message and the transfer fails.

**Comment by justinleewells** [comment]
The most recent push should fix this one.
