### ISSUE TITLE
Error: Cannot find module 'pokemon-go-mitm'

### ISSUE THREAD

**Issue by Lauc1an** [justinleewells/pogo-optimizer#206]
After starting i got this error:
> pogo-optimizer@1.3.2 start /home/laucian/pogo-optimizer
> gulp && node index

[06:59:27] Using gulpfile ~/pogo-optimizer/gulpfile.js
[06:59:27] Starting 'clean'...
[06:59:27] Finished 'clean' after 275 ms
[06:59:27] Starting 'jade'...
[06:59:28] Starting 'stylus'...
[06:59:28] Starting 'img'...
[06:59:28] Starting 'lib-js'...
[06:59:28] Starting 'lib-css'...
[06:59:28] Starting 'favicon'...
[06:59:28] Starting 'js'...
[06:59:28] Starting 'font'...
[06:59:28] Finished 'lib-css' after 569 ms
[06:59:28] Finished 'favicon' after 569 ms
[06:59:29] Finished 'stylus' after 1.02 s
[06:59:29] Finished 'lib-js' after 1.32 s
[06:59:29] Finished 'js' after 1.33 s
[06:59:29] Finished 'jade' after 1.39 s
[06:59:29] Finished 'font' after 1.81 s
[06:59:30] Finished 'img' after 2.91 s
[06:59:30] Starting 'default'...
[06:59:30] Finished 'default' after 15 μs

module.js:340
    throw err;
          ^
Error: Cannot find module 'pokemon-go-mitm'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/laucian/pogo-optimizer/index.js:23:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by nelsonzheng** [comment]
Did you execute the [Common commands?](https://github.com/justinleewells/pogo-optimizer#common)

```
git clone https://github.com/justinleewells/pogo-optimizer
cd pogo-optimizer
npm install
npm run install-libs
npm start
```
`npm install` should install all the node packages that you need.
Just in case, check that `pokemon-go-mitm: "^1.6.0,"` is included under dependencies in the `package.json` file.

**Comment by Lauc1an** [comment]
Yes, I execute all Common commands with out errors, and even install pokemon-go-mitm from npm, but still same error
