### ISSUE TITLE
HTTPS_CLIENT_ERROR

### ISSUE THREAD

**Issue by OStarforge** [justinleewells/pogo-optimizer#37]
I am getting "HTTPS_CLIENT_ERROR" when trying to log in. I am wondering if anyone has advice on this issue. Below is what the Terminal is giving me when I try to open the app:

starting server for appload.ingest.crittercism.com
starting server for bootstrap.upsight-api.com
https server started for appload.ingest.crittercism.com on 59818
https server started for bootstrap.upsight-api.com on 59819
starting server for pgorelease.nianticlabs.com
https server started for pgorelease.nianticlabs.com on 59822
starting server for single.upsight-api.com
https server started for single.upsight-api.com on 59823
HTTPS_CLIENT_ERROR on : { [Error: socket hang up] code: 'ECONNRESET' }
HTTPS_CLIENT_ERROR on : { [Error: socket hang up] code: 'ECONNRESET' }
HTTPS_CLIENT_ERROR on : { [Error: socket hang up] code: 'ECONNRESET' }

**Comment by artvol11** [comment]
This error still persists for me as well

**Comment by artvol11** [comment]
Some extended info using longjohn (i don't know what to make of this, but here you go 
HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:820:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }

**Comment by justinleewells** [comment]
So I actually think this has to do with the proxy library that the pokemon-go-mitm library uses. Not 100% sure, but I know that the maintainer is replacing the proxy library with hoxy as we speak.

**Comment by artvol11** [comment]
So hopefully next update should fix this issue? Also was looking at node's open issues and ECONNRESET is still an open issue
[https://github.com/molnarg/node-http2/issues/194](url)

**Comment by artvol11** [comment]
mine appears to be working now, i reinstalled the certificate to do fix my error

**Comment by OStarforge** [comment]
I also reinstalled my certificate and it solved the issue :)
