### ISSUE TITLE
Failed to connect to the phone with socket hang up issues

### ISSUE THREAD

**Issue by quincygogo** [justinleewells/pogo-optimizer#46]
I have successfully run the app and when I start the game on my phone I see the following errors:

HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:820:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }
HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:820:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }
HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:820:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }

The app shows a empty page, no pokemons are shown

Does anyone know how to fix these issues? 

Thank you very much!

Quincy

**Comment by quincygogo** [comment]
More errors:


HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:820:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }
starting server for p31-buy.itunes.apple.com
https server started for p31-buy.itunes.apple.com on 49188
HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:820:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }
starting server for itunes.apple.com
https server started for itunes.apple.com on 49190
HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:820:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }

**Comment by quincygogo** [comment]
Do I need to install the certificate on my laptop only or do I also need to accept it on my phone/

**Comment by justinleewells** [comment]
You only need to install it on your phone. It was generated and lives on your laptop. Try re-pulling and reinstalling the entire thing.

**Comment by quincygogo** [comment]
Thank you very much for your reply.

I can connect to the game but can't see any pokemons. And then after I catch one, I can see the one I just caught. 

How do I fix that?

Thanks,

**Comment by justinleewells** [comment]
`git pull && rm -rf node_modules && npm install`

**Comment by quincygogo** [comment]
Great that works!
