### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by gabzsa** [justinleewells/pogo-optimizer#7]
Hey, I am getting this after npm install:

```
npm WARN package.json pogo-optimizer@0.0.2 No repository field.
-
> node-protobuf@1.3.0 install /Users/gabzsa/pogo/node_modules/pokemon-go-mitm/node_modules/pokemongo-protobuf/node_modules/node-protobuf
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
lp.sh: line 2: pkg-config: command not found
gyp: Call to 'sh lp.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gabzsa/pogo/node_modules/pokemon-go-mitm/node_modules/pokemongo-protobuf/node_modules/node-protobuf
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-protobuf@1.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gabzsa/pogo/npm-debug.log

```

**Comment by queso** [comment]
You need to `brew install protobuf` first, then run this `LIBPROTOBUF=/usr/local/lib/protobuf npm install node-protobuf`. Seem to work for me.

**Comment by andrewda** [comment]
Refer to #1 - as @queso said, you'll need to install protobuf.

**Comment by gabzsa** [comment]
Thanks for the suggestions. You also need to:
`brew install pkg-config`
