### ISSUE TITLE
Latest files failed to build 

### ISSUE THREAD

**Issue by liudayu** [justinleewells/pogo-optimizer#83]
I used `git pull` to update to the latest version, it failed after I entered `npm start`

Tims-MacBook-Pro:~ Tim$  cd pogo-optimizer
Tims-MacBook-Pro:pogo-optimizer Tim$ npm start
> pogo-optimizer@1.1.0 start /Users/Tim/pogo-optimizer
> gulp && node index

(node:35147) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[21:01:24] Using gulpfile ~/pogo-optimizer/gulpfile.js
[21:01:24] Starting 'clean'...
[21:01:24] Finished 'clean' after 3.88 ms
[21:01:24] Starting 'jade'...
[21:01:24] Starting 'stylus'...
[21:01:24] Starting 'img'...
[21:01:24] Starting 'lib-js'...
[21:01:24] Starting 'lib-css'...
[21:01:25] Starting 'favicon'...
[21:01:25] Starting 'js'...
[21:01:25] Starting 'font'...
[21:01:25] Finished 'favicon' after 322 ms
[21:01:25] Finished 'lib-css' after 373 ms
[21:01:25] Finished 'stylus' after 458 ms
[21:01:25] Finished 'lib-js' after 503 ms
[21:01:25] Finished 'js' after 572 ms
[21:01:25] Finished 'jade' after 598 ms
[21:01:25] Finished 'font' after 634 ms
[21:01:26] Finished 'img' after 1.48 s
[21:01:26] Starting 'default'...
[21:01:26] Finished 'default' after 5.95 μs
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
Pokemon GO Optimizer front-end listening on port 3000
Accept the cert at undefined:3000/ca.pem if you haven't already done so
fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/Tim/pogo-optimizer/lib/../data/save/xxxxxxxxxx/player-settings.json'
  at Error (native)
  at Object.fs.openSync (fs.js:634:18)
  at Object.fs.readFileSync (fs.js:502:33)
  at Object.readFileSync (/Users/Tim/pogo-optimizer/node_modules/jsonfile/index.js:61:20)
  at Player.load (/Users/Tim/pogo-optimizer/lib/player.js:22:25)
  at /Users/Tim/pogo-optimizer/index.js:31:14
  at PokemonGoMITM.handleResponse (/Users/Tim/pogo-optimizer/node_modules/pokemon-go-mitm/lib/pokemon-go-mitm.coffee:216:14)
  at /Users/Tim/pogo-optimizer/node_modules/pokemon-go-mitm/lib/pokemon-go-mitm.coffee:174:28
  at /Users/Tim/pogo-optimizer/node_modules/http-mitm-proxy/lib/proxy.js:1010:12
  at /Users/Tim/pogo-optimizer/node_modules/async/lib/async.js:181:20
  at Object.async.forEachOf.async.eachOf (/Users/Tim/pogo-optimizer/node_modules/async/lib/async.js:233:13)
  at Object.async.forEach.async.each (/Users/Tim/pogo-optimizer/node_modules/async/lib/async.js:209:22)
  at Proxy._onResponseEnd (/Users/Tim/pogo-optimizer/node_modules/http-mitm-proxy/lib/proxy.js:1009:9)
  at end (/Users/Tim/pogo-optimizer/node_modules/http-mitm-proxy/lib/proxy.js:846:20)
  at Gunzip.onend (_stream_readable.js:517:10)
  at Gunzip.g (events.js:286:16)
  at emitNone (events.js:91:20)
  at Gunzip.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:934:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! pogo-optimizer@1.1.0 start: `gulp && node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pogo-optimizer@1.1.0 start script 'gulp && node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogo-optimizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogo-optimizer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogo-optimizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Tim/pogo-optimizer/npm-debug.log
Tims-MacBook-Pro:pogo-optimizer Tim$ 

## The npm-debug.log says:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.3.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.6
3 info using node@v6.2.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pogo-optimizer@1.1.0~prestart: pogo-optimizer@1.1.0
6 silly lifecycle pogo-optimizer@1.1.0~prestart: no script for prestart, continuing
7 info lifecycle pogo-optimizer@1.1.0~start: pogo-optimizer@1.1.0
8 verbose lifecycle pogo-optimizer@1.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle pogo-optimizer@1.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Tim/pogo-optimizer/node_modules/.bin:/usr/local/Cellar/node/6.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle pogo-optimizer@1.1.0~start: CWD: /Users/Tim/pogo-optimizer
11 silly lifecycle pogo-optimizer@1.1.0~start: Args: [ '-c', 'gulp && node index' ]
12 silly lifecycle pogo-optimizer@1.1.0~start: Returned: code: 1  signal: null
13 info lifecycle pogo-optimizer@1.1.0~start: Failed to exec start script
14 verbose stack Error: pogo-optimizer@1.1.0 start: `gulp && node index`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid pogo-optimizer@1.1.0
16 verbose cwd /Users/Tim/pogo-optimizer
17 error Darwin 16.0.0
18 error argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.2.2
20 error npm  v3.10.6
21 error code ELIFECYCLE
22 error pogo-optimizer@1.1.0 start: `gulp && node index`
22 error Exit status 1
23 error Failed at the pogo-optimizer@1.1.0 start script 'gulp && node index'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pogo-optimizer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp && node index
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pogo-optimizer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pogo-optimizer
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by liudayu** [comment]
Deleted the whole pogo-optimizer folder and reinstalled pam file on my device somehow fixed the problem.
