### ISSUE TITLE
"npm start" causing error

### ISSUE THREAD

**Issue by ManiacMike** [justinleewells/pogo-optimizer#86]
ENV: Mac OSX 
every commands run without error.
while run "npm start"

macbook:pogo-optimizer Mike$ npm start

> pogo-optimizer@1.1.0 start /Users/Mike/Documents/node/pogo-optimizer
> gulp && node index

module.js:327
    throw err;
    ^

Error: Cannot find module 'source-map'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Mike/Documents/node/pogo-optimizer/node_modules/gulp-jade/node_modules/jade/node_modules/clean-css/lib/stringifier/source-maps.js:1:88)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by justinleewells** [comment]
What version of node are you running? Was this working before v1.0.0?

**Comment by NWinocur** [comment]
Am experiencing a similar but non-identical issue in Ubuntu LTS 16.04 with a pull from master.  First attempt to use the program, so have no basis for comparison with behavior vs prior versions such as v1.0.0:

> pogo-optimizer@1.1.0 start <my path to >/pogo-optimizer
> gulp && node index

/<path to>/pogo-optimizer/gulpfile.js:13
gulp.task('clean', function (cb) {

TypeError: gulp.task is not a function
  at Object.<anonymous> (<path to> gulpfile   
...

**Comment by justinleewells** [comment]
@NWinocur Mind making a separate issue since it's not identical?

**Comment by NWinocur** [comment]
Will do

**Comment by ManiacMike** [comment]
thanks for reply

macbook:pogo-optimizer Mike$ node -v
v4.4.4
macbook:pogo-optimizer Mike$ npm -v
2.15.1

**Comment by justinleewells** [comment]
Mind upgrading to the newest version of node/npm, deleting the node_modules folder, and doing a fresh npm install?

**Comment by ManiacMike** [comment]
Upgrading node to v6.3.1 solves my problem
